[package]
name = "firebase-admin-sdk-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "rustls-tls", "multipart"] }
reqwest-middleware = { version = "0.3", features = ["json"] }
reqwest-retry = "0.5"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "9"
yup-oauth2 = "8"
thiserror = "1.0"
url = "2.5"
anyhow = "1.0"
async-trait = "0.1"
hyper-rustls = "0.24"
hyper = "0.14"
http = "1.0"
futures = "0.3.31"